// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN4HK9emlKyzpEuT7lxoyBkWMJSankQ70',
    appId: '1:1070091804437:web:5f723dbcb021a18964531c',
    messagingSenderId: '1070091804437',
    projectId: 'flutterapplication-22410204',
    authDomain: 'flutterapplication-22410204.firebaseapp.com',
    storageBucket: 'flutterapplication-22410204.firebasestorage.app',
    measurementId: 'G-NR7KW4DBE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNEhu3z43mqEIaI8R7MrXwIonEsVQK81E',
    appId: '1:1070091804437:android:83750b08a2678cef64531c',
    messagingSenderId: '1070091804437',
    projectId: 'flutterapplication-22410204',
    storageBucket: 'flutterapplication-22410204.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHUORgJRqPImNEDksKnDC_-cW7Svw4k0Y',
    appId: '1:1070091804437:ios:d54525dd11faf2f864531c',
    messagingSenderId: '1070091804437',
    projectId: 'flutterapplication-22410204',
    storageBucket: 'flutterapplication-22410204.firebasestorage.app',
    androidClientId: '1070091804437-0invm6b49f6pkr8b0idtck50guq5mtm3.apps.googleusercontent.com',
    iosClientId: '1070091804437-tnes2efo02o1p18813bmkqt23oc4jr15.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHUORgJRqPImNEDksKnDC_-cW7Svw4k0Y',
    appId: '1:1070091804437:ios:d54525dd11faf2f864531c',
    messagingSenderId: '1070091804437',
    projectId: 'flutterapplication-22410204',
    storageBucket: 'flutterapplication-22410204.firebasestorage.app',
    androidClientId: '1070091804437-0invm6b49f6pkr8b0idtck50guq5mtm3.apps.googleusercontent.com',
    iosClientId: '1070091804437-tnes2efo02o1p18813bmkqt23oc4jr15.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN4HK9emlKyzpEuT7lxoyBkWMJSankQ70',
    appId: '1:1070091804437:web:2825a2531b54ef0f64531c',
    messagingSenderId: '1070091804437',
    projectId: 'flutterapplication-22410204',
    authDomain: 'flutterapplication-22410204.firebaseapp.com',
    storageBucket: 'flutterapplication-22410204.firebasestorage.app',
    measurementId: 'G-32D6BZH03Z',
  );

}